import React from 'react'
import Sidebar from '../Components/Sidebar/Sidebar'
import styles from "./page.module.scss"
import Link from 'next/link'

const page = () => {
    return (
        <div className={styles.container}>
            <Sidebar />
            <div className={styles.info}>
                <h1>Disclaimer</h1>
                <p className={styles.heading}>THE USE OF THE WEBSITE BY THE USER / CLIENT SHALL MEAN THAT HE / SHE AGREES WITH THE FOLLOWING TERMS OF USE.</p>
                <p>The present web site, www.hdfcsky.com is owned, operated and maintained by HDFC Securities Limited (hereinafter referred to as “HDFC SECURITIES”), a Company incorporated under the Companies Act, 2013 having CIN: U67120MH2000PLC152193 and having its registered office at Floor 8, I Think Techno Campus, Building-B Alpha, Kanjurmarg (East), Mumbai-400042. This website contains features of services that HDFC Securities Ltd. or its affiliates offer / propose to offer in due course. The services, which are offered, may vary from time to time and are at the sole discretion of HDFC Securities Ltd., subject to regulatory approvals.</p>
                <p>The present web site, www.hdfcsky.com is owned, operated and maintained by HDFC Securities Limited (hereinafter referred to as “HDFC SECURITIES”), a Company incorporated under the Companies Act, 2013 having CIN: U67120MH2000PLC152193 and having its registered office at Floor 8, I Think Techno Campus, Building-B Alpha, Kanjurmarg (East), Mumbai-400042. This website contains features of services that HDFC Securities Ltd. or its affiliates offer / propose to offer in due course. The services, which are offered, may vary from time to time and are at the sole discretion of HDFC Securities Ltd., subject to regulatory approvals.</p>
                <p>This service does not constitute an offer to sell or a solicitation to any person in any jurisdiction where it is unlawful to make such an offer or solicitation.</p>
                <p>The distribution of service / content may be restricted by law, and hence its user / client agrees to bound by the limitation. This service is not intended to be any form of an investment advertisement, investment advice or investment information and has not been registered under any securities law of any foreign jurisdiction and is only for the information of any person in any jurisdiction where it may be lawful to offer such a service.</p>
                <p>Further, no information, market analysis, research report, etc. on this web site or sent to any person through any means is to be construed as a representation with respect to shares, securities or other investment regarding the legality of an investment therein under the respective applicable investment or similar laws or regulations of any person or entity accessing this web site.</p>
                <p>This service is provided 'AS IS' and WHERE-IS basis, without any warranty. HDFC Securities Ltd. and its owners/ affiliates disclaim any warranty of any kind, imputed by the laws of any jurisdiction, whether express or implied, as to any matter whatsoever relating to this service, including without limitation the implied warranties of merchantability, fitness for a particular purpose, and non infringement. HDFC Securities Ltd. considers itself and intends to be subject to the jurisdiction only of the courts of the Republic of India at Mumbai.</p>
                <p>Use of this service is at the sole risk of the user / client. The data and information provided in the web site is not professional advice and should not be relied upon as such. HDFC Securities Ltd. may at any time edit, alter and or remove any information in whole or in part that may be available on this website and that it shall not be held responsible for all or any actions that may subsequently result into any loss, damage and or liability. Nothing contained herein is to be construed as a recommendation to use any product or process, and HDFC Securities Ltd. makes no representation or warranty, express or implied that, the use thereof will not infringe any patent, or otherwise.</p>
                <p>Neither the information, nor any opinion contained on this website or in the research reports / calls constitute a solicitation or offer by HDFC Securities Ltd. or its owners / affiliates to buy or sell any securities, futures, options or other financial instruments or provide any investment advice or service. Any owner / affiliate of HDFC Securities Ltd. and others associated with it may make markets or specialise in, have positions in and effect transactions in securities of companies mentioned herein and may also perform or seek to perform investment banking services for those companies. HDFC Securities Ltd. and/or their owners / affiliates or their employees have or may have a long or short position or holding in the securities, options on securities or other related investments of issuers and companies mentioned herein.</p>
                <p>The investments discussed or recommended in reports / calls and on website of HDFC Securities Ltd. may not be suitable for all investors. Investors must make their own investment decisions based on their specific investment objectives and financial position and using such independent advisors, as they believe necessary.</p>
                <p>Information herein is believed to be reliable however HDFC Securities Ltd. does not warrant its completeness or accuracy. Although HDFC Securities Ltd. tries to ensure that all information and materials in relation to the products, services, facilities, offerings or otherwise provided as part of its website or through any other source of communication, is correct at the time of inclusion on the communication, it does not guarantee the accuracy of the information.</p>
                <p>The content of the articles and the interpretation of data are solely the personal views of the contributors and do not in any way reflect the views of HDFC Securities Ltd. or its owners / affiliates. Users are advised to peruse the articles and other data in the web site only for their information and to rely on their own judgment when making investment decisions.</p>
                <p>HDFC Securities Ltd. and its owners / affiliates are not liable for damages or injury, including without limitation, damages or injury caused by any performance, failure of performance, error, omission, interruption, deletion, defect, delay in operation or transmission, computer virus, communications line failure, theft or destruction or unauthorized access to, alteration of, or use of information, whether resulting, in whole or in part, from, negligence or otherwise.</p>
                <p>HDFC Securities Ltd. along with its directors, employees, associates or other representatives and its Affiliates (along with its directors, employees, associates or other representatives) shall not be liable for damages or injury arising out of or in connection with the use of the Website or its non-use including non-availability, compensatory, direct, indirect or consequential damages, loss of data, income or profit, loss of or damage to property (including without limitation loss of profits, loss or corruption of data, loss of goodwill, work stoppage, computer failure or malfunction, or interruption of business); under any contract, negligence, strict liability or other theory arising out of or relating in any way to the website, site-related services, or any products or services and claims of third parties damages.</p>
                <p>Some jurisdictions do not allow the exclusion of implied warranties, so the above exclusion may not apply to the user / client. HDFC Securities Ltd. makes no guarantees or representations as to, and shall have no liability for, any electronic content delivered by any third party, including, without limitation, the accuracy, subject matter, quality or timeliness of any electronic content. The linked sites are not under control of HDFC Securities Ltd. and HDFC Securities Ltd. is not responsible for the contents of any linked site or any link contained in a linked site, or any changes or updates to such sites. HDFC Securities Ltd. is providing these links to the users / clients only as a convenience, and the inclusion of any link do not imply endorsement by HDFC Securities Ltd. of the site. No judgment or warranty is made with respect to the accuracy, timeliness, or suitability of the content of other services or sites to which these screens link, and HDFC Securities Ltd. and its owners / affiliates take no responsibility therefore. A link to a service or site outside of www.hdfcsky.com is not an endorsement of the service or site, its content, or its sponsoring organization. By providing access to other websites, neither HDFC Securities Ltd. nor its owners / affiliates recommends the purchase or sale of the securities issued by it nor does it endorse the services provided by its sponsoring organization.</p>
                <p>The contents of this website is strictly confidential to the recipient, may not be downloaded to the press or other media, may not be reproduced in any form and may not be sent into the United States or given to any US person (within the meaning of regulations under the US Securities Act of 1933), including any branch or agency of a non-US constituted located in the United States. Failure to comply with this restriction may constitute a violation of the US securities laws. This material may not be sent into Canada or to any Canadian person. This material may not be sent into Japan. In Hong Kong, this material may not be distributed or passed to any person other than a person whose ordinary business it is to buy or sell shares or debentures, whether as principal or as agent. The distribution of this material in other jurisdictions may be restricted by law and persons into whose possession this material comes should inform themselves about, and observe, any such restrictions.</p>
                <p>Accessing or using www.hdfcsky.com in any manner, voluntarily or otherwise in a country or jurisdiction wherein the terms and conditions contained in this disclaimer, in part or in full, are not recognized or not capable of being enforced, then such access or use shall be deemed to be unauthorized. If the user / client downloads any information or software from this site, the user / client agrees to not copy it or remove or obscure any copyright or other notices or legends contained in any such information.</p>
                <p>Orders, if accepted during off market hours will be sent to the exchange after the exchange opens on the next trading day. HDFC Securities Ltd. does not take any responsibility for any delay in acceptance / execution or non-execution of the order by the Exchange.</p>
                <p>“BSE Ltd is not in any manner answerable, responsible or liable to any person or persons for any acts of omission or commission, errors, mistakes and/or violation, actual or perceived, by us or our partners, agents, associates etc., of any of the Rules, Regulations, Bye-laws of BSE Ltd, SEBI Act or any other laws in force from time to time.</p>
                <p>BSE Ltd is not answerable, responsible or liable for any information on this Website or for any services rendered by our employees, our servants, and us.</p>
                <p><span className={styles.sideheading}>Standard Disclaimer</span>
                Investments in securities market are subject to market risks, read all the related documents carefully before investing. Registration granted by SEBI, membership of BASL (in case of IAs) and certification from NISM in no way guarantee performance of the intermediary or provide any assurance of returns to investors.
                </p>
                <p><span className={styles.sideheading}>Mutual Fund</span>
                HSL is a Mutual fund distributor/s registered for Mutual Funds. Mutual fund investments are subject to market risks, read all scheme related documents carefully. Mutual Funds are not an approved product of the Exchanges and any dispute related to this will not be dealt at Exchange platform.
                </p>
                <p><span className={styles.sideheading}>Global Investing, Insurance, Basket Investing, DigiGold, Sovereign Gold Bond, and NPS</span>
                Global Investing, Insurance, Basket Investing, DigiGold, Sovereign Gold Bond, and NPS are not a Exchange traded product and all disputes related to the distribution activity of Global Investing, Insurance, Basket Investing, DigiGold, Sovereign Gold Bond, and NPS will not have access to Exchange investor redressal forum or Arbitration mechanism.
                </p>
                <p><span className={styles.sideheading}>Global Investing</span>
                Involvement of HDFC securities is restricted to Referral only. HDFC securities does not offer this product directly to customers. https://www.hdfcsec.com/globalinvesting.
                </p>
                <p><span className={styles.sideheading}>IPO</span>
                These are illustrative details available in public domain. The securities quoted are exemplary and are not recommendatory
                </p>
                <p><span className={styles.sideheading}>MTF</span>
                MTF is subject to the provisions of SEBI Circular CIR/MRD/DP/54/2017 dated June 13, 2017 and the terms and conditions mentioned in rights and obligations statement issued by HDFC Securities Ltd.
                </p>
                <p className={styles.sideheading}>Brokerage</p>
                <p>
                Brokerage will not exceed the SEBI prescribed limit. <br />
                Disclaimer & SEBI Registration Details: https://www.hdfcsec.com/article/disclaimer-1795.
                </p>
                <ul>
                    <li>ZERO Brokerage up to 75 Orders for the first 30 day time period after onboarding. (Offer Valid till 31st July only)</li>
                    <li>The offer will expire either on completion of 30 days from onboarding OR upto 75 Orders whichever is earlier</li>
                    <li>Post the offer-period, a normal brokerage fee is charged i.e. ₹20 or 2.5% whichever is lower. For more details visit - <Link className={styles.redirectLink} href="https://hdfcsky.com/pricing">https://hdfcsky.com/pricing</Link></li>
                    <li>HDFC Securities reserves the right, in its absolute discretion, to change, alter or discontinue the offer as well as terms & conditions from time to time without further notice</li>
                </ul>
                <p>SEBI Registration No: INZ000186937 (NSE, BSE, MSEI, MCX) |NSE Trading Member Code: 11094 | BSE Clearing Number: 393 | MSEI Trading Member Code: 30000 | MCX Member Code: 56015 | IN-DP-372-2018 (CDSL, NSDL) | CDSL DP ID: 12095000 | NSDL DP ID: IN304279 | AMFI Reg No: ARN -13549 | PFRDA Reg. No: POP 11092018 | IRDA Corporate Agent Licence No: CA0062 | Research Analyst Reg. No: INH000002475 | Investment Adviser: INA000011538-Type-Non Individual | Validity of Registration: Perpetual, Principal Officer.</p>
                <p>Registered Address: iThink Techno Campus, Building - B, Alpha, Office Floor 8, Near Kanjurmarg Station, Kanjurmarg (East), Mumbai - 400042 | Tel: 022-30753400 | Compliance Officer: Mr. Murli V Karkera | Ph: 022-3045 3600 | Email: complianceofficer@hdfcsec.com.</p>
                <p>HDFC Securities has a proprietary trading desk. This desk maintains an arm’s length distance with the Research team and all its activities are segregated from Research activities. The proprietary desk operates independently, potentially leading to investment decisions that may deviate from research views.  </p>
            </div>
        </div>
    )
}

export default page